export const items = [
  {
    d100: [1, 2],
    name: "Mortar and Pestle",
    desc: "Well used, but still functional.",
    gold: 2,
  },
  {
    d100: [3, 4],
    name: "Spices",
    desc: "A small tin containing some aromatic spices used for cooking.",
    gold: 3,
  },
  {
    d100: [5, 6],
    name: "Leather Bag",
    desc: "With a cleaning and a good leather polish this should sell for a few gold.",
    gold: 4,
  },
  {
    d100: [7, 8],
    name: "Tiny Whistle",
    desc: "Very well made with some tiny initials etched into it.",
    gold: 6,
  },
  {
    d100: [9, 10],
    name: "Wooden Abacus",
    desc: "a little damaged in places but usable.",
    gold: 7,
  },
  {
    d100: [11, 12],
    name: "Worn Key",
    desc: "A small worn key.",
    gold: 8,
    effect: "keys+1",
  },
  {
    d100: [13, 14],
    name: "Food",
    desc: "A sealed pouch containing some dry rations.",
    gold: 10,
    effect: "food+1",
  },
  {
    d100: [15, 16],
    name: "Tinderbox",
    desc: "A nice compact tinder box that still works.",
    gold: 12,
  },
  {
    d100: [17, 18],
    name: "Lantern Oil",
    desc: "A glass vial filled with oil.",
    gold: 15,
    effect: "oil+1",
  },
  {
    d100: [19, 20],
    name: "Lock Picks",
    desc: "Held together by some yarn are some lock picks.",
    gold: 15,
    effect: "picks+3",
  },
  {
    d100: [21, 22],
    name: "Rusty Key",
    desc: "A rusty key.",
    gold: 20,
    effect: "keys+1",
  },
  {
    d100: [23, 24],
    name: "Food",
    desc: "A small leather bag containing some dry rations.",
    gold: 20,
    effect: "food+2",
  },
  {
    d100: [25, 26],
    name: "Rope",
    desc: "Around 20 feet of good climbing rope.",
    gold: 21,
  },
  {
    d100: [27, 28],
    name: "Book of Ancient History",
    desc: "A dusty tome probably very valuable is fold to a scholar.",
    gold: 23,
  },
  {
    d100: [29, 30],
    name: "Silver Walking Stick",
    desc: "The walking stick is badly damaged and probably not worth much.",
    gold: 29,
  },
  {
    d100: [31, 32],
    name: "Iron Key",
    desc: "A delicate iron key.",
    gold: 30,
    effect: "keys+1",
  },
  {
    d100: [33, 34],
    name: "Lantern Oil",
    desc: "A small leather flask filled with oil.",
    gold: 30,
    effect: "oil+2",
  },
  {
    d100: [35, 36],
    name: "Silver Pipe",
    desc: "In excellent condition, it looks like it has hardly been used.",
    gold: 34,
  },
  {
    d100: [37, 38],
    name: "Money Pouch",
    desc: "The pouch contains some gold coins.",
    gold: 35,
  },
  {
    d100: [39, 40],
    name: "Brew of Lesser Dmg",
    desc: "Drink to gain +1 Dmg to your next damage roll.",
    gold: 35,
  },
  {
    d100: [41, 42],
    name: "Silver Plate",
    desc: "Finely crafted, the plate looks valuable.",
    gold: 38,
  },
  {
    d100: [43, 44],
    name: "Lock Picks",
    desc: "A pouch containing a selection of lock picks.",
    gold: 40,
    effect: "picks+8",
  },
  {
    d100: [45, 46],
    name: "Bone Key",
    desc: "Carved in bone.",
    gold: 42,
    effect: "keys+1",
  },
  {
    d100: [47, 48],
    name: "Lantern Oil",
    desc: "Secured in a small barrel is some oil.",
    gold: 45,
    effect: "oil+3",
  },
  {
    d100: [49, 50],
    name: "Brew of Lesser Str",
    desc: "Drink to gain +3 Str to your next d100 roll.",
    gold: 45,
  },
  {
    d100: [51, 52],
    name: "Brew of Lesser Dex",
    desc: "Drink to gain +3 Dex to your next d100 roll.",
    gold: 45,
  },
  {
    d100: [53, 54],
    name: "Brew of Lesser Int",
    desc: "Drink to gain +3 Int to your next d100 roll.",
    gold: 45,
  },
  {
    d100: [55, 56],
    name: "Silver Candlestick",
    desc: "After a good cleaning it will fetch a decent amount of gold.",
    gold: 49,
  },
  {
    d100: [57, 58],
    name: "Silver Key",
    desc: "A solid silver key.",
    gold: 50,
    effect: "keys+1",
  },
  {
    d100: [59, 60],
    name: "Lock Picks",
    desc: "A tiny tin containing some lock picks.",
    gold: 50,
    effect: "picks+10",
  },
  {
    d100: [61, 62],
    name: "Brew of Lesser Def",
    desc: "Drink to gain +1 Def on a monster's next damage roll.",
    gold: 50,
  },
  {
    d100: [63, 64],
    name: "Writing Set",
    desc: "A boxed writing set with paper, ink and several quills still intact.",
    gold: 52,
  },
  {
    d100: [65, 66],
    name: "Food",
    desc: "In a small basket is some dried meat.",
    gold: 60,
    effect: "food+3",
  },
  {
    d100: [67, 68],
    name: "Money Pouch",
    desc: "The pouch contains some gold coins.",
    gold: 70,
    effect: "gold+70",
  },
  {
    d100: [69, 70],
    name: "Silver Mirror",
    desc: "The silver frame is heavily tarnished but the mirror is still intact.",
    gold: 78,
  },
  {
    d100: [71, 72],
    name: "Keys",
    desc: "A hoop holding 3 keys.",
    gold: 80,
    effect: "keys+3",
  },
  {
    d100: [73, 74],
    name: "Food",
    desc: "A sack of dried food.",
    gold: 80,
    effect: "food+4",
  },
  {
    d100: [75, 76],
    name: "Potion of Lesser Remove Poison",
    desc: "Drink to remove up to 2 shaded pips on the poison track.",
    gold: 80,
  },
  {
    d100: [77, 78],
    name: "Potion of Lesser Healing",
    desc: "Drink to restore up to 4 lost HP.",
    gold: 80,
  },
  {
    d100: [79, 80],
    name: "Silver Crucifix",
    desc: "The cross is very well made and will be worth a fair price.",
    gold: 88,
  },
  {
    d100: [81, 82],
    name: "Potion of Lesser Str",
    desc: "Drink to gain +3 Str until you next increase the time track.",
    gold: 90,
  },
  {
    d100: [83, 84],
    name: "Potion of Lesser Dex",
    desc: "Drink to gain +3 Dex until you next increase the time track.",
    gold: 90,
  },
  {
    d100: [85, 86],
    name: "Potion of Lesser Int",
    desc: "Drink to gain +3 Int until you next increase the time track.",
    gold: 90,
  },
  {
    d100: [87, 88],
    name: "Book of Skill",
    desc: "Roll 1d10 and gain +5 skill bonus to the skill rolled.",
    gold: 0,
  },
  {
    d100: [89, 90],
    name: "Golden Key",
    desc: "A solid gold key.",
    gold: 110,
    effect: "keys+1",
  },
  {
    d100: [91, 92],
    name: "Potion of Lesser Cure Disease",
    desc: "Drink to remove up to 2 shaded pips on the disease track.",
    gold: 130,
  },
  {
    d100: [93, 94],
    name: "Money Pouch",
    desc: "The pouch contains some gold coins.",
    gold: 140,
    effect: "gold+140",
  },
  {
    d100: [95, 96],
    name: "Bag of Gems",
    desc: "Several precious gems are found in a leather pouch.",
    gold: 290,
  },
  {
    d100: [97],
    name: "Skeleton Key",
    desc: "Roll 1d10 to attempt to open any locked door or chest.",
    gold: 300,
  },
  {
    d100: [98],
    name: "Potion of Lesser Fate",
    desc: "Drink to add +20 to a result when rolling on the next table.",
    gold: 400,
  },
  {
    d100: [99, 100],
    name: "Treasure",
    desc: "A treasure is found - TA.",
    gold: 0,
  },
];
