export const ta = [
  {
    d100: [1, 2, 3],
    name: "Silver Pieces",
    desc: "A small bag filled with silver coins.",
    gold: 70,
    effect: "gold+70",
  },
  {
    d100: [4, 5, 6],
    name: "Brew of Finer Dmg",
    desc: "Drink to gain +2 Dmg to your next damage roll.",
    gold: 70,
  },
  {
    d100: [7, 8, 9],
    name: "Brew of Finer Str",
    desc: "Drink to gain +5 Str to your next d100 roll.",
    gold: 75,
  },
  {
    d100: [10, 11, 12],
    name: "Brew of Finer Dex",
    desc: "Drink to gain +5 Dex to your next d100 roll.",
    gold: 75,
  },
  {
    d100: [13, 14, 15],
    name: "Brew of Finer Int",
    desc: "Drink to gain +5 Int to your next d100 roll.",
    gold: 75,
  },
  {
    d100: [
      16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
      34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
    ],
    name: "Objective Item",
    desc: "An Objective Item is found that may be required for a quest. If it's not needed for the quest, it is instead a Fine Item worth 100gp.",
    gold: 100,
  },
  {
    d100: [47, 48, 49],
    name: "Brew of Finer Def",
    desc: "Drink to gain +2 Def on a monster's next damage roll.",
    gold: 100,
  },
  {
    d100: [50, 51, 52],
    name: "Finer Armor",
    desc: 'Roll on Table A - Armor and add "Finer" before its name. It gains +0.2 Def.',
    gold: 0,
  },
  {
    d100: [53, 54, 55],
    name: "Finer Weapon",
    desc: 'Roll on Table W - Weapon and add "Finer" before its name. It gains +1 Dmg.',
    gold: 0,
  },
  {
    d100: [56, 57, 58],
    name: "Silver Pieces",
    desc: "A small bag filled with silver coins.",
    gold: 140,
    effect: "gold+140",
  },
  {
    d100: [59, 60, 61],
    name: "Potion of Finer Str",
    desc: "Drink to gain +5 Str until you next increase the time track.",
    gold: 150,
  },
  {
    d100: [62, 63, 64],
    name: "Potion of Finer Dex",
    desc: "Drink to gain +5 Dex until you next increase the time track.",
    gold: 150,
  },
  {
    d100: [65, 66, 67],
    name: "Potion of Finer Int",
    desc: "Drink to gain +5 Int until you next increase the time track.",
    gold: 150,
  },
  {
    d100: [68, 69, 70],
    name: "Potion of Finer Remove Poison",
    desc: "Drink to remove up to 4 shaded pips on the poison track.",
    gold: 160,
  },
  {
    d100: [71, 72, 73],
    name: "Potion of Finer Healing",
    desc: "Drink to restore up to 8 lost HP.",
    gold: 160,
  },
  {
    d100: [74, 75, 76],
    name: "Elixir of Finer Fate",
    desc: "Drink to gain 1 Fate point.",
    gold: 160,
  },
  {
    d100: [77, 78, 79],
    name: "Scroll",
    desc: "You find a parchment containing a spell.",
    gold: 200,
  },
  {
    d100: [80, 81, 82],
    name: "Potion of Finer Cure Disease",
    desc: "Drink to remove up to 4 shaded pips on the disease track.",
    gold: 260,
  },
  {
    d100: [83, 84, 85],
    name: "Silver Pieces",
    desc: "A small bag filled with silver coins.",
    gold: 280,
    effect: "gold+280",
  },
  {
    d100: [86, 87, 88],
    name: "Elixir of Finer Str",
    desc: "Drink to gain 1 point of primary Str.",
    gold: 300,
  },
  {
    d100: [89, 90, 91],
    name: "Elixir of Finer Dex",
    desc: "Drink to gain 1 point of primary Dex.",
    gold: 300,
  },
  {
    d100: [92, 93, 94],
    name: "Elixir of Finer Int",
    desc: "Drink to gain 1 point of primary Int.",
    gold: 300,
  },
  {
    d100: [95],
    name: "Elixir of Finer Health",
    desc: "Drink to gain 1 point of primary HP.",
    gold: 400,
  },
  {
    d100: [96],
    name: "Potion of Finer Fate",
    desc: "Drink to add +40 to a result when rolling on the next table.",
    gold: 800,
  },
  {
    d100: [97],
    name: "Elixir of Finer Life",
    desc: "Drink to gain 1 Life point.",
    gold: 1000,
  },
  {
    d100: [98],
    name: "Greater Treasure",
    desc: "A much greater treasure is found - TB.",
    gold: 0,
  },
  {
    d100: [99],
    name: "Legendary Ring",
    desc: "Roll on table L for its legend and value.",
    gold: 0,
  },
  {
    d100: [100],
    name: "Legendary Necklace",
    desc: "Roll on table L for its legend and value.",
    gold: 0,
  },
];
