export const tb = [
  {
    d100: [1, 2, 3],
    name: "Brew of Greater Dmg",
    desc: "Drink to gain +3 Dmg to your next damage roll.",
    gold: 105,
  },
  {
    d100: [4, 5, 6],
    name: "Gold Pieces",
    desc: "A small bag filled with gold coins.",
    gold: 140,
    effect: "gold+140",
  },
  {
    d100: [7, 8, 9],
    name: "Brew of Greater Def",
    desc: "Drink to gain +3 Def on a monster's next damage roll.",
    gold: 150,
  },
  {
    d100: [10, 11, 12],
    name: "Brew of Greater Str",
    desc: "Drink to gain +10 Str to your next d100 roll.",
    gold: 150,
  },
  {
    d100: [13, 14, 15],
    name: "Brew of Greater Dex",
    desc: "Drink to gain +10 Dex to your next d100 roll.",
    gold: 150,
  },
  {
    d100: [
      16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
      34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
    ],
    name: "Objective Item",
    desc: "An Objective Item is found that may be required for a quest. If it's not needed for the quest, it is instead a Great Item worth 150gp.",
    gold: 150,
  },
  {
    d100: [47, 48, 49],
    name: "Brew of Greater Int",
    desc: "Drink to gain +10 Int to your next d100 roll.",
    gold: 150,
  },
  {
    d100: [50, 51, 52],
    name: "Greater Armor",
    desc: 'Roll on Table A - Armor and add "Greater" before its name. It gains +0.4 Def.',
    gold: 0,
  },
  {
    d100: [53, 54, 55],
    name: "Greater Weapon",
    desc: 'Roll on Table W - Weapon and add "Greater" before its name. It gains +2 Dmg.',
    gold: 0,
  },
  {
    d100: [56, 57, 58],
    name: "Potion of Greater Remove Poison",
    desc: "Drink to remove up to 6 shaded pips on the poison track.",
    gold: 240,
  },
  {
    d100: [59, 60, 61],
    name: "Potion of Greater Healing",
    desc: "Drink to restore up to 12 lost HP.",
    gold: 240,
  },
  {
    d100: [62, 63, 64],
    name: "Gold Pieces",
    desc: "A small bag filled with gold coins.",
    gold: 280,
    effect: "gold+280",
  },
  {
    d100: [65, 66, 67],
    name: "Potion of Greater Str",
    desc: "Drink to gain +10 Str until you next increase the time track.",
    gold: 300,
  },
  {
    d100: [68, 69, 70],
    name: "Potion of Greater Dex",
    desc: "Drink to gain +10 Dex until you next increase the time track.",
    gold: 300,
  },
  {
    d100: [71, 72, 73],
    name: "Potion of Greater Int",
    desc: "Drink to gain +10 Int until you next increase the time track.",
    gold: 300,
  },
  {
    d100: [74, 75, 76],
    name: "Potion of Greater Cure Disease",
    desc: "Drink to remove up to 6 shaded pips on the disease track.",
    gold: 390,
  },
  {
    d100: [77, 78, 79],
    name: "Elixir of Greater Fate",
    desc: "Drink to gain 2 Fate points.",
    gold: 400,
  },
  {
    d100: [80, 81, 82],
    name: "Gold Pieces",
    desc: "A small bag filled with gold coins.",
    gold: 560,
    effect: "gold+560",
  },
  {
    d100: [83, 84, 85],
    name: "Elixir of Greater Health",
    desc: "Drink to gain 2 points of primary HP.",
    gold: 800,
  },
  {
    d100: [86, 87, 88],
    name: "Spell Book",
    desc: "You find a damaged book that contains a spell written inside.",
    gold: 800,
  },
  {
    d100: [89, 90, 91],
    name: "Elixir of Greater Str",
    desc: "Drink to gain 3 points of primary Str.",
    gold: 900,
  },
  {
    d100: [92, 93],
    name: "Elixir of Greater Dex",
    desc: "Drink to gain 3 points of primary Dex.",
    gold: 900,
  },
  {
    d100: [94],
    name: "Elixir of Greater Int",
    desc: "Drink to gain 3 point of primary Int.",
    gold: 900,
  },
  {
    d100: [95],
    name: "Potion of Greater Fate",
    desc: "Drink to add +60 to a result when rolling on the next table.",
    gold: 1200,
  },
  {
    d100: [96],
    name: "Elixir of Greater Life",
    desc: "Drink to gain 3 Life points.",
    gold: 3000,
  },
  {
    d100: [97],
    name: "Superior Treasure",
    desc: "A much greater treasure is found - TC.",
    gold: 0,
  },
  {
    d100: [98],
    name: "Legendary Ring",
    desc: "Roll on table L for its legend and value.",
    gold: 0,
  },
  {
    d100: [99],
    name: "Legendary Necklace",
    desc: "Roll on table L for its legend and value.",
    gold: 0,
  },
  {
    d100: [100],
    name: "Legendary Weapon",
    desc: "Roll on table W for a weapon and then on table L for its legend and value.",
    gold: 0,
  },
];
