export const tb = [
  {
    d100: [1, 2, 3],
    name: "Brew of Superior Dmg",
    desc: "Drink to gain +4 Dmg to your next damage roll.",
    gold: 140,
  },
  {
    d100: [4, 5, 6],
    name: "Brew of Superior Def",
    desc: "Drink to gain +4 Def on a monster's next damage roll.",
    gold: 200,
  },
  {
    d100: [7, 8, 9],
    name: "Brew of Superior Str",
    desc: "Drink to gain +15 Str to your next d100 roll.",
    gold: 225,
  },
  {
    d100: [10, 11, 12],
    name: "Brew of Superior Dex",
    desc: "Drink to gain +15 Dex to your next d100 roll.",
    gold: 225,
  },
  {
    d100: [13, 14, 15],
    name: "Brew of Superior Int",
    desc: "Drink to gain +15 Int to your next d100 roll.",
    gold: 225,
  },
  {
    d100: [
      16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
      34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
    ],
    name: "Objective Item",
    desc: "An Objective Item is found that may be required for a quest. If it's not needed for the quest, it is instead a Superior Item worth 250gp.",
    gold: 250,
  },
  {
    d100: [47, 48, 49],
    name: "Gemstones",
    desc: "A small bag filled with valuable gemstones.",
    gold: 280,
    effect: "gold+280",
  },
  {
    d100: [50, 51, 52],
    name: "Superior Armor",
    desc: 'Roll on Table A - Armor and add "Superior" before its name. It gains +0.6 Def.',
    gold: 0,
  },
  {
    d100: [53, 54, 55],
    name: "Superior Weapon",
    desc: 'Roll on Table W - Weapon and add "Superior" before its name. It gains +3 Dmg.',
    gold: 0,
  },
  {
    d100: [56, 57, 58],
    name: "Potion of Superior Remove Poison",
    desc: "Drink to remove up to 8 shaded pips on the poison track.",
    gold: 320,
  },
  {
    d100: [59, 60, 61],
    name: "Potion of Superior Healing",
    desc: "Drink to restore up to 16 lost HP.",
    gold: 320,
  },
  {
    d100: [62, 63, 64],
    name: "Potion of Superior Str",
    desc: "Drink to gain +15 Str until you next increase the time track.",
    gold: 450,
  },
  {
    d100: [65, 66, 67],
    name: "Potion of Superior Dex",
    desc: "Drink to gain +15 Dex until you next increase the time track.",
    gold: 450,
  },
  {
    d100: [68, 69, 70],
    name: "Potion of Superior Int",
    desc: "Drink to gain +15 Int until you next increase the time track.",
    gold: 450,
  },
  {
    d100: [71, 72, 73],
    name: "Potion of Superior Cure Disease",
    desc: "Drink to remove up to 8 shaded pips on the disease track.",
    gold: 520,
  },
  {
    d100: [74, 75, 76],
    name: "Gemstones",
    desc: "A small bag filled with valuable gemstones.",
    gold: 560,
    effect: "gold+560",
  },
  {
    d100: [77, 78, 79],
    name: "Elixir of Superior Fate",
    desc: "Drink to gain 3 Fate points.",
    gold: 600,
  },
  {
    d100: [80, 81, 82],
    name: "Gemstones",
    desc: "A small bag filled with valuable gemstones.",
    gold: 1120,
    effect: "gold+1120",
  },
  {
    d100: [83, 84, 85],
    name: "Elixir of Superior Health",
    desc: "Drink to gain 3 points of primary HP.",
    gold: 800,
  },
  {
    d100: [86, 87, 88],
    name: "Elixir of Superior Str",
    desc: "Drink to gain 5 points of primary Str.",
    gold: 1500,
  },
  {
    d100: [89, 90, 91],
    name: "Elixir of Superior Dex",
    desc: "Drink to gain 5 points of primary Dex.",
    gold: 1500,
  },
  {
    d100: [92, 93],
    name: "Elixir of Superior Int",
    desc: "Drink to gain 5 point of primary Int.",
    gold: 1500,
  },
  {
    d100: [94],
    name: "Spell Book",
    desc: "You find a damaged book that contains two spells written inside.",
    gold: 1600,
  },
  {
    d100: [95],
    name: "Potion of Superior Fate",
    desc: "Drink to add +80 to a result when rolling on the next table.",
    gold: 1600,
  },
  {
    d100: [96],
    name: "Elixir of Superior Life",
    desc: "Drink to gain 5 Life points.",
    gold: 5000,
  },
  {
    d100: [97],
    name: "Legendary Ring",
    desc: "Roll on table L for its legend and value.",
    gold: 0,
  },
  {
    d100: [98],
    name: "Legendary Necklace",
    desc: "Roll on table L for its legend and value.",
    gold: 0,
  },
  {
    d100: [99],
    name: "Legendary Weapon",
    desc: "Roll on table W for a weapon and then on table L for its legend and value.",
    gold: 0,
  },
  {
    d100: [100],
    name: "Legendary Armor",
    desc: "Roll on table A for armor and then on table L for its legend and value.",
    gold: 0,
  },
];
